language: C

addons:
  apt:
    packages:
      - autoconf
      - automake
      - gawk
      - lcov
      - libtool
      - pkg-config
      - valgrind
  homebrew:
    packages:
      - autoconf
      - automake
      - gawk
      - libtool
      - pkg-config

branches:
  except:
    - master

cache:
  - ccache
  - pip

git:
  depth: false

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#libxcrypt"
    skip_join: true

dist: xenial
sudo: false

matrix:
  fast_finish: true
  include:
    - name: "macOS, Clang, all hashes, obsolete API"
      compiler: clang
      os: osx
      env:
        - CONF="--enable-obsolete-api --enable-hashes=all"

install:
  - ./.travis_install.sh

before_script:
  - ./.travis_before_script.sh

script:
  - ./.travis_script.sh

after_success:
  - ./.travis_after_success.sh
